apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
        - name: nginx
          image: 574436675271.dkr.ecr.us-east-1.amazonaws.com/my-nginx-app
          ports:
            - containerPort: 80
