name: Terraform Plan

on:
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: Infrastructure

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: Infrastructure

      - name: Terraform Validate
        run: terraform validate
        working-directory: Infrastructure

      - name: Terraform Plan
        run: terraform plan
        working-directory: Infrastructure
